In [4]:
# %matplotlib inline
# %config InlineBackend.figure_format = 'retina'

In [5]:
import pandas as pd
import numpy as np
from pykrx import bond
from pykrx import stock
import matplotlib.pyplot as plt
import warnings


# plt.style.use('seaborn')
# plt.style.use('seaborn-colorblind') #alternative
plt.rcParams['figure.figsize'] = [8, 4.5]
plt.rcParams['figure.dpi'] = 300
warnings.simplefilter(action='ignore', category=FutureWarning)

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
samsung = stock.get_market_ohlcv("20200101", "20201231", "005930")

In [ ]:
from datetime import datetime
import backtrader as bt

In [ ]:
class SmaSignal(bt.Signal):
    params = (('period', 20), )
    
    def __init__(self):
        self.lines.signal = self.data - bt.ind.SMA(period=self.p.period)

In [ ]:
samsung

               시가     고가     저가     종가       거래량           거래대금   등락률
날짜
2020-01-02  55500  56000  55000  55200  12993228   719663194492 -1.08
2020-01-03  56000  56600  54900  55500  15422255   860206709400  0.54
2020-01-06  54900  55600  54600  55500  10278951   567461518576  0.00
2020-01-07  55700  56400  55600  55800  10009778   560226659600  0.54
2020-01-08  56200  57400  55900  56800  23501171  1330939275000  1.79
...           ...    ...    ...    ...       ...            ...   ...
2020-12-23  72400  74000  72300  73900  19411326  1419205113900  2.21
2020-12-24  74100  78800  74000  77800  32502870  2486986812800  5.28
2020-12-28  79000  80100  78200  78700  40085044  3172810866091  1.16
2020-12-29  78800  78900  77300  78300  30339449  2368814098000 -0.51
2020-12-30  77400  81300  77300  81000  29417421  2344317462700  3.45

[248 rows x 7 columns]

In [ ]:
# 백트레이더를 사용하기 위해서는 이에 맞춰서 데이터를 변경시켜주어야함
samsung = samsung.drop(['거래대금','등락률'], axis=1)
samsung = samsung.rename(columns={'시가':'open', '고가':'high', '저가':'low', '종가':'close', '거래량':'volume'})

In [ ]:
samsung

             open   high    low  close    volume
날짜
2020-01-02  55500  56000  55000  55200  12993228
2020-01-03  56000  56600  54900  55500  15422255
2020-01-06  54900  55600  54600  55500  10278951
2020-01-07  55700  56400  55600  55800  10009778
2020-01-08  56200  57400  55900  56800  23501171
...           ...    ...    ...    ...       ...
2020-12-23  72400  74000  72300  73900  19411326
2020-12-24  74100  78800  74000  77800  32502870
2020-12-28  79000  80100  78200  78700  40085044
2020-12-29  78800  78900  77300  78300  30339449
2020-12-30  77400  81300  77300  81000  29417421

[248 rows x 5 columns]

In [ ]:
samsung["open"]=samsung["open"].apply(pd.to_numeric,errors="coerce")
samsung["high"]=samsung["high"].apply(pd.to_numeric,errors="coerce")
samsung["low"]=samsung["low"].apply(pd.to_numeric,errors="coerce")
samsung["close"]=samsung["close"].apply(pd.to_numeric,errors="coerce")
samsung["volume"]=samsung["volume"].apply(pd.to_numeric,errors="coerce")

In [ ]:
samsung = bt.feeds.PandasData(dataname=samsung)

In [ ]:
cerebro = bt.Cerebro(stdstats = False)

cerebro.adddata(samsung)
cerebro.broker.setcash(100000)
cerebro.add_signal(bt.SIGNAL_LONG, SmaSignal)
cerebro.addobserver(bt.observers.BuySell)
cerebro.addobserver(bt.observers.Value)

In [ ]:
print(f'Starting Portfolio Value: {cerebro.broker.getvalue():.2f}')
cerebro.run()
print(f'Final Portfolio Value: {cerebro.broker.getvalue():.2f}')

Starting Portfolio Value: 100000.00
Final Portfolio Value: 118750.00

In [ ]:
cerebro.plot(iplot=True, volume=False)

ImportError: cannot import name 'warnings' from 'matplotlib.dates' (c:\Users\OPERATOR-70\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\dates.py)

In [ ]:
!pip install matplo

Requirement already satisfied: pip in c:\users\operator-70\appdata\local\programs\python\python310\lib\site-packages (22.0.4)
Collecting pip
  Downloading pip-22.3.1-py3-none-any.whl (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 10.9 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.4
    Uninstalling pip-22.0.4:
      Successfully uninstalled pip-22.0.4
Successfully installed pip-22.3.1
Note: you may need to restart the kernel to use updated packages.